# Generated by Django 3.2.3 on 2021-05-16 10:38

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ArchiveIP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archive', models.FileField(upload_to='archives', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['7z', 'tar', 'gz', 'zip', 'rar', 'arc', 'jar'])], verbose_name='Архив')),
                ('ip', models.GenericIPAddressField()),
                ('uploaded_at', models.DateField(default=datetime.date(2021, 5, 16), verbose_name='Дата загрузки')),
            ],
            options={
                'ordering': ['uploaded_at'],
            },
        ),
    ]
